version: '3.9'

services:
  pg:
    image: postgres:latest
    container_name: pg
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5555:80

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - 7700:7700
